<?php
//ERROR CONTROL OPERATOR
$y = @file('foo.txt');
$x = file('foo.txt'); //No such file or directory 
//PHP supports one error control operator: the at sign (@). 
//When prepended to an expression in PHP, any diagnostic 
//error that might be generated by that expression will be suppressed.
//NOTE: NOT RECOMMENDED

//INCREMENT/DECREMENT OPERATOR
$x = 5;
echo ++$x; //6 //PRE INCREMENT
echo --$x; //5 //PRE DECREMENT
echo $x++; //5 //POST INCREMENT 
echo $x; //6 (result of post increment)
echo $x--; //6 POST DECREMENT
echo $x; //5  //(result of post decrement)
